project_name: reconmapd

before:
  hooks:
    - go mod download

builds:
  - id: "reconmapd"
    main: ./cmd/reconmapd/main.go
    binary: reconmapd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
      - -X main.builtBy=goreleaser
      - -X github.com/reconmap/reconmapd/internal/build.BuildVersion={{.Version}}
      - -X github.com/reconmap/reconmapd/internal/build.BuildTime={{.CommitDate}}
      - -X github.com/reconmap/reconmapd/internal/build.BuildCommit={{.Commit}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

release:
  extra_files:
    - glob: sbom.spdx.json

brews:
  - name: reconmapd
    homepage: "https://github.com/reconmap/agent"
    description: "Reconmapd: The Reconmap agent allows clients to launch commands remotely, open interactive browser terminals, and receive push notifications."
    folder: Formula
    license: "GPL-3.0"
    commit_author:
      name: Santiago Lizardo
      email: santiagolizardo@users.noreply.github.com
    tap:
      owner: reconmap
      name: homebrew-tap
    install: |
      bin.install "reconmapd"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
